export const PORT="8000"
export const MONGODB_URI="mongodb+srv://admin:z26a1i9d4@cluster0.fpg8ly3.mongodb.net/videotube"
export const CORS_ORIGIN="*"
export const ACCESS_TOKEN_SECRET="hhJHHMkkjfb7jgcGg-5fCYhvf"
export const ACCESS_TOKEN_EXPIRY="1000d"
export const REFRESH_TOKEN_SECRET="jhvCgugugvkKJN-668VCFcfuh"
export const REFRESH_TOKEN_EXPIRY="1000d"

export const CLOUDINARY_CLOUD_NAME="dmunw7keq"
export const CLOUDINARY_API_KEY="974886933419486"
export const CLOUDINARY_API_SECRET="4uOfKa1xjnKSi1rVV6wAlH4kvmA"